name: CI test
on: push
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          python-version: ${{matrix.python-version}}
        
      - name: Install Dependencies
        run: | 
          python3 -m pip install --upgrade pip
          pip install -r ./requirements.txt
        
      - name: Run tests
        run: python3 test_app.py

